# -*- coding: utf-8 -*-
"""Cl.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qLGrA_jw3UP6HDKl-f1p0mBaWSIMIJbD

Cleaner Code
"""

!pip install catboost shap imbalanced-learn -q

import pandas as pd
import numpy as np
from google.colab import files
import io
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.model_selection import train_test_split, StratifiedKFold
from sklearn.metrics import (accuracy_score, classification_report,
                             balanced_accuracy_score, confusion_matrix, f1_score)
from sklearn.ensemble import RandomForestClassifier
from sklearn.utils.class_weight import compute_sample_weight
from xgboost import XGBClassifier
from catboost import CatBoostClassifier
from imblearn.over_sampling import SMOTE
import shap
import warnings
warnings.filterwarnings('ignore')

# ----------------------------------------------------------------------
# Helper: normalise SHAP output
# ----------------------------------------------------------------------
def normalise_shap(shap_values, n_classes):
    if isinstance(shap_values, list):
        return [np.array(sv)[:, :, 0] if np.array(sv).ndim == 3 else np.array(sv) for sv in shap_values]
    shap_values = np.array(shap_values)
    if shap_values.ndim == 2:
        return [shap_values] * n_classes
    if shap_values.ndim == 3:
        if shap_values.shape[0] == n_classes:
            return [shap_values[i] for i in range(n_classes)]
        elif shap_values.shape[2] == n_classes:
            return [shap_values[:, :, i] for i in range(n_classes)]
    raise ValueError(f"Unexpected SHAP shape: {shap_values.shape}")

# ----------------------------------------------------------------------
# 1. Upload & basic cleaning
# ----------------------------------------------------------------------
print("Upload 'Dataset2.csv'")
uploaded = files.upload()
filename = list(uploaded.keys())[0]
df = pd.read_csv(io.BytesIO(uploaded[filename]))
df.columns = df.columns.str.strip()

orig_rows = df.shape[0]
df = df.drop_duplicates()
print(f"\nDuplicates removed: {orig_rows - df.shape[0]}, rows left: {df.shape[0]}")


# ----------------------------------------------------------------------
# 2. Feature engineering (rank reversal, scores, dummies)
# ----------------------------------------------------------------------
rank_cols = ['Mutual_Funds', 'Equity_Market', 'Debentures',
             'Government_Bonds', 'Fixed_Deposits', 'PPF', 'Gold']
for col in rank_cols:
    if col in df.columns:
        df[col] = 8 - pd.to_numeric(df[col], errors='coerce')

duration_map = {'Less than 1 year':1, '1-3 years':2, '3-5 years':3, 'More than 5 years':4}
expect_map   = {'10%-20%':1, '20%-30%':2, '30%-40%':3}
monitor_map  = {'Monthly':1, 'Weekly':2, 'Daily':3}
df['Duration_Score'] = df['Duration'].map(duration_map).fillna(0)
df['Expect_Score']   = df['Expect'].map(expect_map).fillna(0)
df['Monitor_Score']  = df['Invest_Monitor'].map(monitor_map).fillna(0)

nominal_cols = ['gender','Objective','Purpose','What are your savings objectives?','Stock_Marktet']
df_ml = pd.get_dummies(df, columns=[c for c in nominal_cols if c in df.columns], drop_first=True)

drop_cols = ['Duration','Expect','Invest_Monitor','Reason_Equity','Reason_Mutual',
             'Reason_Bonds','Reason_FD','Avenue','Investment_Avenues','Factor','Source']
df_ml = df_ml.drop(columns=[c for c in drop_cols if c in df_ml.columns])

num_cols = df_ml.select_dtypes(include=np.number).columns
df_ml[num_cols] = df_ml[num_cols].fillna(df_ml[num_cols].mean())
df_ml = df_ml.fillna(0)

obj_cols = df_ml.select_dtypes(include='object').columns
if len(obj_cols) > 0:
    df_ml = pd.get_dummies(df_ml, columns=obj_cols, drop_first=True)

# ----------------------------------------------------------------------
# 3. Correlation filter (threshold 0.85)
# ----------------------------------------------------------------------
print("\nCorrelation analysis (threshold = 0.85)")
corr_mat = df_ml.corr().round(2)
plt.figure(figsize=(20,16))
sns.heatmap(corr_mat, annot=True, fmt=".2f", cmap="coolwarm", linewidths=0.3,
            vmin=-1, vmax=1, center=0, annot_kws={"size":7})
plt.title("Full Correlation Matrix")
plt.tight_layout()
plt.show()

THRESH = 0.85
drop_set = set()
cols = corr_mat.columns.tolist()
for i in range(len(cols)):
    for j in range(i+1, len(cols)):
        if abs(corr_mat.iloc[i,j]) >= THRESH:
            drop_set.add(cols[j])
if drop_set:
    print(f"Dropping {drop_set}")
    df_ml = df_ml.drop(columns=list(drop_set))
    rank_cols = [c for c in rank_cols if c not in drop_set]
print(f"Remaining features: {df_ml.shape[1]}")

# ----------------------------------------------------------------------
# 4. W‑KMeans clustering (on all final features)
# ----------------------------------------------------------------------
MAX_WEIGHT_CAP = 0.15

def cap_and_redistribute(weights, cap=MAX_WEIGHT_CAP):
    w = weights.copy()
    for _ in range(100):
        over = w > cap
        if not over.any(): break
        excess = (w[over] - cap).sum()
        w[over] = cap
        under = ~over
        if under.any():
            w[under] += excess * (w[under] / w[under].sum())
    return w / w.sum()

def compute_feature_wcss(X, labels, n_clusters):
    n_feat = X.shape[1]
    wcss = np.zeros(n_feat)
    for k in range(n_clusters):
        pts = X[labels == k]
        if len(pts) > 0:
            wcss += ((pts - pts.mean(axis=0))**2).sum(axis=0)
    return wcss

def wkmeans(X, n_clusters=3, max_iter=50, tol=1e-4, random_state=42, beta=2.0, cap=MAX_WEIGHT_CAP):
    n, m = X.shape
    w = np.ones(m) / m
    prev_w = np.zeros(m)
    for it in range(max_iter):
        Xw = X * np.sqrt(w)
        km = KMeans(n_clusters=n_clusters, random_state=random_state, n_init=10, max_iter=300)
        labels = km.fit_predict(Xw)
        wcss = compute_feature_wcss(X, labels, n_clusters)
        new_w = np.zeros(m)
        for j in range(m):
            if wcss[j] == 0:
                new_w[j] = 1.0
            else:
                denom = np.sum((wcss[j] / (wcss + 1e-10)) ** (1.0/(beta-1)))
                new_w[j] = 1.0 / (denom + 1e-10)
        new_w = new_w / new_w.sum()
        new_w = cap_and_redistribute(new_w, cap=cap)
        if np.max(np.abs(new_w - prev_w)) < tol:
            print(f"  Converged at iteration {it+1}")
            break
        prev_w, w = new_w.copy(), new_w
    else:
        print(f"  Max iterations reached")
    return labels, w

# Scale and run W-KMeans
scaler = StandardScaler()
X_scaled = scaler.fit_transform(df_ml)
print("\nRunning W-KMeans...")
wk_labels, weights = wkmeans(X_scaled, n_clusters=3)

# Create weight DataFrame BEFORE adding cluster column
feature_names = df_ml.columns.tolist()
wdf = pd.DataFrame({'Feature': feature_names, 'Weight': weights}).sort_values('Weight', ascending=False)
print("\nTop 15 feature weights:")
print(wdf.head(15).to_string())
plt.figure(figsize=(14,5))
plt.bar(wdf['Feature'][:15], wdf['Weight'][:15], color='steelblue')
plt.axhline(y=MAX_WEIGHT_CAP, color='red', linestyle='--', label=f'Cap={MAX_WEIGHT_CAP}')
plt.xticks(rotation=45, ha='right', fontsize=8)
plt.title("W-KMeans Feature Weights")
plt.legend()
plt.tight_layout()
plt.show()

# Now add the cluster column
df_ml['WK_Cluster'] = wk_labels

# ----------------------------------------------------------------------
# 5. Label clusters by risk score (Debentures+Equity) - (PPF+Fixed_Deposits)
# ----------------------------------------------------------------------
avail_rank = [c for c in rank_cols if c in df_ml.columns]
profile_cols = ['Expect_Score','Duration_Score','Monitor_Score'] + avail_rank
raw_profiles = df_ml.groupby('WK_Cluster')[profile_cols].mean().round(2)
print("\nRaw cluster profiles:")
print(raw_profiles)

risk = {}
for cid in raw_profiles.index:
    row = raw_profiles.loc[cid]
    risky = row.get('Debentures',0) + row.get('Equity_Market',0)
    safe  = row.get('PPF',0) + row.get('Fixed_Deposits',0)
    risk[cid] = risky - safe

sorted_risk = sorted(risk, key=risk.get)  # low→high
cid_con, cid_mod, cid_agg = sorted_risk

label_map = {cid_con:0, cid_mod:1, cid_agg:2}
df_ml['Risk_Class'] = df_ml['WK_Cluster'].map(label_map)

label_names = {0:'Conservative', 1:'Moderate', 2:'Aggressive'}
palette = {0:'#2196F3', 1:'#FF9800', 2:'#E53935'}
order_ids = [0,1,2]

print("\nFinal cluster profiles:")
final_profiles = df_ml.groupby('Risk_Class')[profile_cols].mean().round(2)
final_profiles.index = [label_names[i] for i in final_profiles.index]
print(final_profiles)

plt.figure(figsize=(10,4))
sns.heatmap(final_profiles.T, annot=True, fmt=".2f", cmap="YlOrRd")
plt.title("Final Cluster Profiles")
plt.tight_layout()
plt.show()

print("\nCluster sizes:")
for lbl in order_ids:
    cnt = (df_ml['Risk_Class']==lbl).sum()
    print(f"  {label_names[lbl]:12}: {cnt:5} ({cnt/len(df_ml)*100:.1f}%)")

# ----------------------------------------------------------------------
# 6. Demographic visualisations (age & gender)
# ----------------------------------------------------------------------
demo = pd.DataFrame({'Risk_Class': df_ml['Risk_Class'], 'Risk_Label': df_ml['Risk_Class'].map(label_names)})
if 'age' in df.columns:
    demo['age'] = pd.to_numeric(df['age'], errors='coerce')
if 'gender' in df.columns:
    demo['gender'] = df['gender'].astype(str).str.strip()

order_labels = [label_names[i] for i in order_ids]
named_pal = {label_names[i]: palette[i] for i in order_ids}

if 'age' in demo.columns:
    fig, axs = plt.subplots(1,3, figsize=(18,5))
    for lbl in order_ids:
        sub = demo[demo['Risk_Class']==lbl]['age'].dropna()
        axs[0].hist(sub, bins=15, alpha=0.5, color=palette[lbl], label=label_names[lbl], edgecolor='black')
    axs[0].set_title("Age Distribution"); axs[0].legend()
    sns.boxplot(data=demo, x='Risk_Label', y='age', order=order_labels, palette=named_pal, ax=axs[1])
    axs[1].set_title("Box Plot")
    mean_age = demo.groupby('Risk_Label')['age'].mean().reindex(order_labels)
    std_age = demo.groupby('Risk_Label')['age'].std().reindex(order_labels)
    axs[2].bar(order_labels, mean_age, yerr=std_age, color=[palette[i] for i in order_ids], capsize=6)
    axs[2].set_title("Mean ± Std")
    plt.suptitle("Age vs Risk Class"); plt.tight_layout(); plt.show()

if 'gender' in demo.columns:
    fig, axs = plt.subplots(1,2, figsize=(14,5))
    gender_cnt = demo.groupby(['Risk_Label','gender']).size().unstack(fill_value=0).reindex(order_labels)
    gender_cnt.plot(kind='bar', ax=axs[0], edgecolor='black', color=['#F48FB1','#90CAF9'])
    axs[0].set_title("Gender Count"); axs[0].set_ylabel("Count")
    gender_pct = gender_cnt.div(gender_cnt.sum(axis=1), axis=0)*100
    gender_pct.plot(kind='bar', stacked=True, ax=axs[1], edgecolor='black', color=['#F48FB1','#90CAF9'])
    axs[1].set_title("Gender %"); axs[1].set_ylabel("%")
    plt.suptitle("Gender vs Risk Class"); plt.tight_layout(); plt.show()

if 'age' in demo.columns and 'gender' in demo.columns:
    pivot = demo.groupby(['gender','Risk_Label'])['age'].mean().unstack().reindex(columns=order_labels)
    plt.figure(figsize=(8,4))
    sns.heatmap(pivot, annot=True, fmt=".1f", cmap="YlOrRd")
    plt.title("Mean age by Gender × Risk Class"); plt.tight_layout(); plt.show()

# ----------------------------------------------------------------------
# 7. Feature vs cluster visualisations (strip, violin, box, bar)
# ----------------------------------------------------------------------
plot_feats = [c for c in profile_cols if c in df_ml.columns]
n_feat = len(plot_feats); n_cols = 3; n_rows = (n_feat + n_cols -1)//n_cols

np.random.seed(42)
fig, axes = plt.subplots(n_rows, n_cols, figsize=(6*n_cols, 3.5*n_rows), constrained_layout=True)
axes = axes.flatten()
for idx, feat in enumerate(plot_feats):
    ax = axes[idx]
    for lbl in order_ids:
        vals = df_ml[df_ml['Risk_Class']==lbl][feat]
        ax.scatter(vals, lbl + np.random.uniform(-0.2,0.2,len(vals)), alpha=0.4, s=14,
                   color=palette[lbl], label=label_names[lbl])
    ax.set_yticks(order_ids); ax.set_yticklabels([label_names[i] for i in order_ids])
    ax.set_xlabel(feat); ax.set_title(feat)
    ax.grid(axis='x', linestyle='--', alpha=0.4)
for idx in range(n_feat, len(axes)): axes[idx].set_visible(False)
handles = [mpatches.Patch(color=palette[k], label=label_names[k]) for k in order_ids]
fig.legend(handles=handles, title="Risk Class", loc='lower right')
fig.suptitle("Strip plots"); plt.show()

df_plot = df_ml[plot_feats + ['Risk_Class']].copy()
df_plot['Risk_Label'] = df_plot['Risk_Class'].map(label_names)
fig2, axes2 = plt.subplots(n_rows, n_cols, figsize=(6*n_cols, 4*n_rows), constrained_layout=True)
axes2 = axes2.flatten()
for idx, feat in enumerate(plot_feats):
    sns.violinplot(data=df_plot, x='Risk_Label', y=feat, order=order_labels, palette=named_pal, ax=axes2[idx])
    axes2[idx].set_title(feat)
for idx in range(n_feat, len(axes2)): axes2[idx].set_visible(False)
fig2.suptitle("Violin plots"); plt.show()

fig3, axes3 = plt.subplots(n_rows, n_cols, figsize=(6*n_cols, 4*n_rows), constrained_layout=True)
axes3 = axes3.flatten()
for idx, feat in enumerate(plot_feats):
    sns.boxplot(data=df_plot, x='Risk_Label', y=feat, order=order_labels, palette=named_pal, ax=axes3[idx])
    axes3[idx].set_title(feat)
for idx in range(n_feat, len(axes3)): axes3[idx].set_visible(False)
fig3.suptitle("Box plots"); plt.show()

means = df_ml.groupby('Risk_Class')[plot_feats].mean().round(2)
means.index = [label_names[i] for i in means.index]
x = np.arange(len(plot_feats)); width=0.25
fig4, ax4 = plt.subplots(figsize=(max(14, len(plot_feats)*1.2),5))
for i, lbl in enumerate(order_ids):
    ax4.bar(x + i*width, means.loc[label_names[lbl]], width, label=label_names[lbl],
            color=palette[lbl], edgecolor='black', alpha=0.85)
ax4.set_xticks(x + width); ax4.set_xticklabels(plot_feats, rotation=45, ha='right')
ax4.set_ylabel("Mean Value"); ax4.set_title("Mean Feature Values")
ax4.legend(); plt.tight_layout(); plt.show()

# ----------------------------------------------------------------------
# 8. Prepare X, y (exclude rank columns and cluster info)
# ----------------------------------------------------------------------
exclude = ['Risk_Class','WK_Cluster','Stock_Marktet_Yes'] + rank_cols
X = df_ml.drop(columns=[c for c in exclude if c in df_ml.columns])
y = df_ml['Risk_Class']
print("\nClass distribution (whole dataset):")
for lbl in order_ids:
    cnt = (y==lbl).sum(); print(f"  {label_names[lbl]:12}: {cnt:5} ({cnt/len(y)*100:.1f}%)")

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)
X_train_arr = X_train.values.astype(float); X_test_arr = X_test.values.astype(float)
y_train_np = y_train.values.flatten(); y_test_np = y_test.values.flatten()

target_names = [label_names[i] for i in order_ids]

# ----------------------------------------------------------------------
# 9. SMOTE and Undersampling (pre‑compute)
# ----------------------------------------------------------------------
sm = SMOTE(random_state=42, k_neighbors=5)
X_sm, y_sm = sm.fit_resample(X_train_arr, y_train_np)
y_sm = y_sm.flatten()

minority_cnt = (y_train_np == 2).sum()
np.random.seed(42)
us_idx = []
for cls in order_ids:
    idx_cls = np.where(y_train_np == cls)[0]
    us_idx.extend(np.random.choice(idx_cls, size=minority_cnt, replace=False))
np.random.shuffle(us_idx)
X_us, y_us = X_train_arr[us_idx], y_train_np[us_idx]

# ----------------------------------------------------------------------
# 10. Unified evaluation function (returns dict for easy key access)
# ----------------------------------------------------------------------
def evaluate_phase(name, X_tr, y_tr, use_class_weight=False, cmap='Blues'):
    print(f"\n{'='*70}\n{name}\n{'='*70}")
    print(f"{'Model':<18} | {'Accuracy':>10} | {'Balanced Acc':>13} | {'Macro F1':>10}")
    print("-"*60)
    results = {}

    # Random Forest
    rf = RandomForestClassifier(n_estimators=100, max_depth=4, random_state=42,
                                class_weight='balanced' if use_class_weight else None)
    rf.fit(X_tr, y_tr)
    yp = rf.predict(X_test_arr).flatten()
    acc = accuracy_score(y_test_np, yp); bal = balanced_accuracy_score(y_test_np, yp); f1 = f1_score(y_test_np, yp, average='macro')
    print(f"{'Random Forest':<18} | {acc:>10.4f} | {bal:>13.4f} | {f1:>10.4f}")
    results['Random Forest'] = {'model': rf, 'y_pred': yp, 'acc': acc, 'bal_acc': bal, 'f1': f1}

    # XGBoost
    xgb = XGBClassifier(n_estimators=100, max_depth=4, random_state=42,
                        eval_metric='mlogloss', use_label_encoder=False)
    if use_class_weight:
        sw = compute_sample_weight('balanced', y=y_tr)
        xgb.fit(X_tr, y_tr, sample_weight=sw)
    else:
        xgb.fit(X_tr, y_tr)
    yp = xgb.predict(X_test_arr).flatten()
    acc = accuracy_score(y_test_np, yp); bal = balanced_accuracy_score(y_test_np, yp); f1 = f1_score(y_test_np, yp, average='macro')
    print(f"{'XGBoost':<18} | {acc:>10.4f} | {bal:>13.4f} | {f1:>10.4f}")
    results['XGBoost'] = {'model': xgb, 'y_pred': yp, 'acc': acc, 'bal_acc': bal, 'f1': f1}

    # CatBoost
    cb = CatBoostClassifier(iterations=100, depth=4, verbose=0, random_state=42)
    if use_class_weight:
        cb.fit(X_tr, y_tr, sample_weight=sw)
    else:
        cb.fit(X_tr, y_tr)
    yp = cb.predict(X_test_arr).flatten()
    acc = accuracy_score(y_test_np, yp); bal = balanced_accuracy_score(y_test_np, yp); f1 = f1_score(y_test_np, yp, average='macro')
    print(f"{'CatBoost':<18} | {acc:>10.4f} | {bal:>13.4f} | {f1:>10.4f}")
    results['CatBoost'] = {'model': cb, 'y_pred': yp, 'acc': acc, 'bal_acc': bal, 'f1': f1}

    # Classification reports
    for model_name, res in results.items():
        print(f"\n--- {model_name} classification report ---")
        print(classification_report(y_test_np, res['y_pred'], target_names=target_names))

    # Confusion matrices
    fig, axes = plt.subplots(1,3, figsize=(18,5))
    for ax, (model_name, res) in zip(axes, results.items()):
        cm = confusion_matrix(y_test_np, res['y_pred'], labels=order_ids)
        sns.heatmap(pd.DataFrame(cm, index=[f"True:{label_names[i]}" for i in order_ids],
                                 columns=[f"Pred:{label_names[i]}" for i in order_ids]),
                    annot=True, fmt='d', cmap=cmap, ax=ax, annot_kws={'size':11,'weight':'bold'})
        ax.set_title(f"{model_name}\n({name})", fontsize=11, fontweight='bold')
    plt.suptitle(f"Confusion matrices – {name}", fontsize=12, fontweight='bold')
    plt.tight_layout(); plt.show()
    return results

# ----------------------------------------------------------------------
# 11. Run four phases
# ----------------------------------------------------------------------
phase1 = evaluate_phase("PHASE 1: NO BALANCING", X_train_arr, y_train_np, use_class_weight=False, cmap='Greys')
phase2 = evaluate_phase("PHASE 2: CLASS WEIGHTING ONLY", X_train_arr, y_train_np, use_class_weight=True, cmap='Blues')
phase3 = evaluate_phase("PHASE 3: SMOTE ONLY", X_sm, y_sm, use_class_weight=False, cmap='Greens')
phase4 = evaluate_phase("PHASE 4: UNDERSAMPLING", X_us, y_us, use_class_weight=False, cmap='Oranges')

# ----------------------------------------------------------------------
# 12. Four‑way comparison
# ----------------------------------------------------------------------
print("\n" + "="*70)
print("FOUR‑WAY COMPARISON")
print("="*70)
for model in ['Random Forest','XGBoost','CatBoost']:
    print(f"\n{model}")
    print(f"{'Metric':<15} {'No Bal':>10} {'CW Only':>10} {'SMOTE':>10} {'Undersamp':>12}")
    print("-"*57)
    for metric, key in [('Accuracy','acc'), ('Balanced Acc','bal_acc'), ('Macro F1','f1')]:
        v1 = phase1[model][key]
        v2 = phase2[model][key]
        v3 = phase3[model][key]
        v4 = phase4[model][key]
        print(f"{metric:<15} {v1:>10.4f} {v2:>10.4f} {v3:>10.4f} {v4:>12.4f}")

# ----------------------------------------------------------------------
# 13. SHAP analysis (using SMOTE‑trained models)
# ----------------------------------------------------------------------
print("\n=== SHAP ANALYSIS (SMOTE models) ===")
feature_names = X.columns.tolist()
X_test_df = pd.DataFrame(X_test_arr, columns=feature_names)
for model_name in ['Random Forest','XGBoost']:
    mdl = phase3[model_name]['model']
    explainer = shap.TreeExplainer(mdl)
    shap_vals = explainer.shap_values(X_test_arr)
    shap_list = normalise_shap(shap_vals, 3)
    for i, cls in enumerate(order_ids):
        plt.figure(figsize=(12,8))
        shap.summary_plot(shap_list[i], X_test_df, feature_names=feature_names, plot_type='dot', show=False, max_display=20)
        plt.title(f"{model_name} SHAP – {label_names[cls]}")
        plt.tight_layout(); plt.show()
    # mean absolute SHAP
    mean_abs = np.mean([np.abs(shap_list[i]) for i in range(3)], axis=0)
    mean_abs_feat = mean_abs.mean(axis=0)
    imp_df = pd.DataFrame({'Feature':feature_names, 'Mean_SHAP':mean_abs_feat}).sort_values('Mean_SHAP', ascending=False).head(15)
    plt.figure(figsize=(10,5))
    plt.barh(imp_df['Feature'][::-1], imp_df['Mean_SHAP'][::-1], color='#E53935')
    plt.xlabel("Mean |SHAP|"); plt.title(f"{model_name} – top 15 features"); plt.tight_layout(); plt.show()

print("\nDone.")

