# -*- coding: utf-8 -*-
"""20/5/26.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KDf5_55iyDuOZGDsZg4iLpUDs0esrVtF
"""

# =============================================================================
# BLOCK 1: INSTALL REQUIRED LIBRARIES
# =============================================================================
!pip install catboost shap imbalanced-learn -q

import pandas as pd
import numpy as np
from google.colab import files
import io
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.model_selection import train_test_split, StratifiedKFold, cross_val_score
from sklearn.metrics import (accuracy_score, classification_report,
                             balanced_accuracy_score, confusion_matrix, f1_score,
                             silhouette_score, davies_bouldin_score, calinski_harabasz_score)
from sklearn.ensemble import RandomForestClassifier
from sklearn.utils.class_weight import compute_sample_weight
from xgboost import XGBClassifier
from catboost import CatBoostClassifier
from imblearn.over_sampling import SMOTE
from imblearn.under_sampling import RandomUnderSampler
from scipy.stats import f_oneway
import warnings
warnings.filterwarnings('ignore')

print("All libraries imported successfully.")

# =============================================================================
# BLOCK 2: UPLOAD AND INSPECT
# =============================================================================
print("Upload 'Dataset2.csv'")
uploaded = files.upload()
filename = list(uploaded.keys())[0]
df = pd.read_csv(io.BytesIO(uploaded[filename]))
df.columns = df.columns.str.strip()

print(f"\nShape: {df.shape}")
print(f"Columns: {df.columns.tolist()}")
print(df.head(3))

orig_rows = df.shape[0]
df = df.drop_duplicates()
print(f"\nDuplicates removed: {orig_rows - df.shape[0]}, rows left: {df.shape[0]}")
# =============================================================================
# BLOCK 3: ENCODING
# =============================================================================

rank_cols = ['Mutual_Funds', 'Equity_Market', 'Debentures',
             'Government_Bonds', 'Fixed_Deposits', 'PPF', 'Gold']
for col in rank_cols:
    df[col] = 8 - pd.to_numeric(df[col], errors='coerce')

# Binary
df['Gender_Score']    = df['gender'].map({'Female': 0, 'Male': 1})
df['Stock_Score']     = df['Stock_Marktet'].map({'No': 0, 'Yes': 1})

# Ordinal — genuine risk progression
df['Duration_Score']  = df['Duration'].map(
    {'Less than 1 year': 1, '1-3 years': 2, '3-5 years': 3, 'More than 5 years': 4})
df['Expect_Score']    = df['Expect'].map(
    {'10%-20%': 1, '20%-30%': 2, '30%-40%': 3})
df['Monitor_Score']   = df['Invest_Monitor'].map(
    {'Monthly': 1, 'Weekly': 2, 'Daily': 3})
df['Objective_Score'] = df['Objective'].map(
    {'Income': 1, 'Capital Appreciation': 2, 'Growth': 3})
df['Avenue_Score']    = df['Avenue'].map(
    {'Public Provident Fund': 1, 'Fixed Deposits': 2, 'Mutual Fund': 3, 'Equity': 4})

# One-hot — all nominal columns (drop_first=True avoids multicollinearity)
nominal_cols = [
    'Factor',
    'Purpose',
    'What are your savings objectives?',
    'Reason_Equity',
    'Reason_Mutual',
    'Reason_Bonds',
    'Reason_FD'
]
df = pd.get_dummies(df, columns=nominal_cols, drop_first=True)

# Collect OHE column groups
reason_ohe_cols = [c for c in df.columns if any(
    c.startswith(p) for p in [
        'Reason_Equity_', 'Reason_Mutual_',
        'Reason_Bonds_', 'Reason_FD_'
    ]
)]

supervised_ohe_cols = [c for c in df.columns if any(
    c.startswith(p) for p in [
        'Factor_', 'Purpose_',
        'What are your savings objectives?_'
    ]
)]

print("\nEncoding complete.")
print(f"Reason OHE cols for clustering ({len(reason_ohe_cols)}): {reason_ohe_cols}")
print(f"Supervised OHE cols ({len(supervised_ohe_cols)}): {supervised_ohe_cols}")
print("\nMissing values:")
check = rank_cols + ['Gender_Score','Stock_Score','Duration_Score','Expect_Score',
                     'Monitor_Score','Objective_Score','Avenue_Score']
print(df[check].isnull().sum())
# =============================================================================
# BLOCK 4: FEATURE SETS
# =============================================================================

# CLUSTERING: rank cols + reason OHE cols (drop_first dummies, no false ordinal)
CLUSTER_FEATURES = rank_cols

# SUPERVISED: demographics + ordinal stated prefs + supervised OHE cols
SUPERVISED_FEATURES = [
    'age', 'Gender_Score', 'Stock_Score',
    'Duration_Score', 'Expect_Score', 'Monitor_Score',
    'Objective_Score', 'Avenue_Score'
] + supervised_ohe_cols

print(f"\nClustering features ({len(CLUSTER_FEATURES)}): {CLUSTER_FEATURES}")
print(f"Supervised features ({len(SUPERVISED_FEATURES)}): {SUPERVISED_FEATURES}")
# =============================================================================
# BLOCK 5: CORRELATION CHECK ON CLUSTERING FEATURES
# =============================================================================
corr_clust = df[CLUSTER_FEATURES].corr().round(2)
plt.figure(figsize=(12, 9))
sns.heatmap(corr_clust, annot=True, fmt=".2f", cmap="coolwarm",
            vmin=-1, vmax=1, center=0, annot_kws={"size": 8})
plt.title("Correlation Matrix — Clustering Features")
plt.tight_layout()
plt.show()

THRESH = 0.85
drop_set = set()
cols = corr_clust.columns.tolist()
for i in range(len(cols)):
    for j in range(i + 1, len(cols)):
        if abs(corr_clust.iloc[i, j]) >= THRESH:
            drop_set.add(cols[j])

if drop_set:
    print(f"\nDropping {len(drop_set)} highly correlated clustering features: {drop_set}")
    CLUSTER_FEATURES = [c for c in CLUSTER_FEATURES if c not in drop_set]
    rank_cols = [c for c in rank_cols if c not in drop_set]
else:
    print("\nNo clustering features exceeded the correlation threshold.")

# =============================================================================
# BLOCK 6: W-KMEANS CLUSTERING
# =============================================================================
MAX_WEIGHT_CAP = 0.15

def cap_and_redistribute(weights, cap=MAX_WEIGHT_CAP):
    w = weights.copy()
    for _ in range(100):
        over = w > cap
        if not over.any(): break
        excess = (w[over] - cap).sum()
        w[over] = cap
        under = ~over
        if under.any():
            w[under] += excess * (w[under] / w[under].sum())
    return w / w.sum()

def compute_feature_wcss(X, labels, n_clusters):
    wcss = np.zeros(X.shape[1])
    for k in range(n_clusters):
        pts = X[labels == k]
        if len(pts) > 0:
            wcss += ((pts - pts.mean(axis=0)) ** 2).sum(axis=0)
    return wcss

def wkmeans(X, n_clusters=3, max_iter=50, tol=1e-4, random_state=42, beta=2.0, cap=MAX_WEIGHT_CAP):
    n, m = X.shape
    w = np.ones(m) / m
    prev_w = np.zeros(m)
    for it in range(max_iter):
        Xw = X * np.sqrt(w)
        km = KMeans(n_clusters=n_clusters, random_state=random_state, n_init=10, max_iter=300)
        labels = km.fit_predict(Xw)
        wcss = compute_feature_wcss(X, labels, n_clusters)
        new_w = np.zeros(m)
        for j in range(m):
            if wcss[j] == 0:
                new_w[j] = 1.0
            else:
                denom = np.sum((wcss[j] / (wcss + 1e-10)) ** (1.0 / (beta - 1)))
                new_w[j] = 1.0 / (denom + 1e-10)
        new_w = new_w / new_w.sum()
        new_w = cap_and_redistribute(new_w, cap=cap)
        if np.max(np.abs(new_w - prev_w)) < tol:
            print(f"  W-KMeans converged at iteration {it + 1}")
            break
        prev_w, w = new_w.copy(), new_w
    else:
        print("  W-KMeans: max iterations reached")
    return labels, w

scaler_clust = StandardScaler()
X_clust = scaler_clust.fit_transform(df[CLUSTER_FEATURES])

print("\nRunning W-KMeans...")
wk_labels, weights = wkmeans(X_clust, n_clusters=3)

wdf = pd.DataFrame({'Feature': CLUSTER_FEATURES, 'Weight': weights}).sort_values('Weight', ascending=False)
print("\nFeature weights:")
print(wdf.to_string(index=False))

plt.figure(figsize=(12, 4))
plt.bar(wdf['Feature'], wdf['Weight'], color='steelblue')
plt.axhline(y=MAX_WEIGHT_CAP, color='red', linestyle='--', label=f'Cap={MAX_WEIGHT_CAP}')
plt.xticks(rotation=45, ha='right', fontsize=9)
plt.title("W-KMeans Feature Weights")
plt.legend()
plt.tight_layout()
plt.show()

df['WK_Cluster'] = wk_labels

# =============================================================================
# BLOCK 7: RISK LABEL ASSIGNMENT
# =============================================================================
risk_weights = {
    'Equity_Market':    2.0,   # most aggressive — highest positive
    'Mutual_Funds':     1.0,   # moderately aggressive
    'Debentures':      -0.5,   # corporate debt — mildly conservative
    'Gold':            -0.5,   # defensive/safe-haven asset
    'PPF':             -1.0,   # long-lock-in gov instrument — conservative
    'Government_Bonds': -1.5,  # sovereign debt — strongly conservative
    'Fixed_Deposits':  -2.0,   # most conservative — highest negative
}

avail_rank = [c for c in rank_cols if c in df.columns]
profile_cols = avail_rank + ['ReasonEq_Score', 'ReasonMut_Score', 'ReasonBonds_Score', 'ReasonFD_Score']
raw_profiles = df.groupby('WK_Cluster')[avail_rank].mean().round(2)

risk_scores = {}
for cid in raw_profiles.index:
    score = sum(risk_weights.get(a, 0) * raw_profiles.loc[cid, a]
                for a in risk_weights if a in raw_profiles.columns)
    risk_scores[cid] = score

sorted_risk = sorted(risk_scores, key=risk_scores.get)
cid_con, cid_mod, cid_agg = sorted_risk
label_map = {cid_con: 0, cid_mod: 1, cid_agg: 2}
df['Risk_Class'] = df['WK_Cluster'].map(label_map)

label_names = {0: 'Conservative', 1: 'Moderate', 2: 'Aggressive'}
palette = {0: '#2196F3', 1: '#FF9800', 2: '#E53935'}
order_ids = [0, 1, 2]
order_labels = [label_names[i] for i in order_ids]
named_pal = {label_names[i]: palette[i] for i in order_ids}

print("\n=== FINAL RISK CLASS SIZES ===")
for lbl in order_ids:
    cnt = (df['Risk_Class'] == lbl).sum()
    print(f"  {label_names[lbl]:12}: {cnt:5} ({cnt / len(df) * 100:.1f}%)")

print("\nRisk scores per cluster (monotonicity check):")
for lbl in order_ids:
    orig_cid = [k for k, v in label_map.items() if v == lbl][0]
    print(f"  {label_names[lbl]:12}: {risk_scores[orig_cid]:.3f}")

# =============================================================================
# BLOCK 8: CLUSTERING VALIDATION
# =============================================================================
print("\n" + "=" * 60)
print("W-KMEANS CLUSTER QUALITY EVALUATION")
print("=" * 60)

sil = silhouette_score(X_clust, wk_labels)
db  = davies_bouldin_score(X_clust, wk_labels)
ch  = calinski_harabasz_score(X_clust, wk_labels)
print(f"\nInternal metrics:")
print(f"  Silhouette score   : {sil:.4f}  (>0.25 acceptable for survey data; >0.4 good)")
print(f"  Davies-Bouldin idx : {db:.4f}  (lower is better)")
print(f"  Calinski-Harabasz  : {ch:.1f}  (higher is better)")

print(f"\nANOVA: separation across risk classes")
print(f"{'Feature':<25} {'F-stat':>10} {'p-value':>12} {'Significant?':>14}")
print("-" * 65)
for feat in CLUSTER_FEATURES:
    groups = [df[df['Risk_Class'] == k][feat].dropna().values for k in [0, 1, 2]]
    f_stat, p_val = f_oneway(*groups)
    sig = "YES ✓" if p_val < 0.05 else "no"
    print(f"{feat:<25} {f_stat:>10.2f} {p_val:>12.4f} {sig:>14}")

# Heatmap of cluster profiles
final_profiles = df.groupby('Risk_Class')[avail_rank].mean().round(2)
final_profiles.index = [label_names[i] for i in final_profiles.index]
plt.figure(figsize=(10, 4))
sns.heatmap(final_profiles.T, annot=True, fmt=".2f", cmap="YlOrRd")
plt.title("Cluster Profiles — Mean Investment Avenue Preference per Risk Class")
plt.tight_layout()
plt.show()

# Elbow + silhouette vs k
X_w = X_clust * np.sqrt(weights)
wcss_list, sil_list = [], []
k_range = range(2, 8)
for k in k_range:
    km_tmp = KMeans(n_clusters=k, random_state=42, n_init=10).fit(X_w)
    wcss_list.append(km_tmp.inertia_)
    sil_list.append(silhouette_score(X_w, km_tmp.labels_))

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 4))
ax1.plot(k_range, wcss_list, 'o-', color='steelblue')
ax1.axvline(x=3, color='red', linestyle='--', label='k=3 chosen')
ax1.set_title("Elbow curve"); ax1.set_xlabel("k"); ax1.set_ylabel("WCSS"); ax1.legend()
ax2.plot(k_range, sil_list, 's-', color='darkorange')
ax2.axvline(x=3, color='red', linestyle='--', label='k=3 chosen')
ax2.set_title("Silhouette vs k"); ax2.set_xlabel("k"); ax2.set_ylabel("Silhouette"); ax2.legend()
plt.tight_layout(); plt.show()

# =============================================================================
# BLOCK 9: DEMOGRAPHIC ANALYSIS
# =============================================================================
demo = df[['Risk_Class']].copy()
demo['Risk_Label'] = demo['Risk_Class'].map(label_names)
demo['age'] = pd.to_numeric(df['age'], errors='coerce')
demo['gender'] = df['gender'].astype(str).str.strip()

fig, axs = plt.subplots(1, 3, figsize=(18, 5))
for lbl in order_ids:
    sub = demo[demo['Risk_Class'] == lbl]['age'].dropna()
    axs[0].hist(sub, bins=15, alpha=0.5, color=palette[lbl], label=label_names[lbl], edgecolor='black')
axs[0].set_title("Age Distribution by Risk Class"); axs[0].legend()
sns.boxplot(data=demo, x='Risk_Label', y='age', order=order_labels, palette=named_pal, ax=axs[1])
axs[1].set_title("Age Box Plot")
mean_age = demo.groupby('Risk_Label')['age'].mean().reindex(order_labels)
std_age  = demo.groupby('Risk_Label')['age'].std().reindex(order_labels)
axs[2].bar(order_labels, mean_age, yerr=std_age, color=[palette[i] for i in order_ids], capsize=6)
axs[2].set_title("Mean Age ± Std")
plt.suptitle("Age vs Risk Class"); plt.tight_layout(); plt.show()

fig, axs = plt.subplots(1, 2, figsize=(14, 5))
gender_cnt = demo.groupby(['Risk_Label', 'gender']).size().unstack(fill_value=0).reindex(order_labels)
gender_cnt.plot(kind='bar', ax=axs[0], edgecolor='black', color=['#F48FB1', '#90CAF9'])
axs[0].set_title("Gender Count per Risk Class"); axs[0].set_ylabel("Count")
gender_pct = gender_cnt.div(gender_cnt.sum(axis=1), axis=0) * 100
gender_pct.plot(kind='bar', stacked=True, ax=axs[1], edgecolor='black', color=['#F48FB1', '#90CAF9'])
axs[1].set_title("Gender Proportion (%)"); axs[1].set_ylabel("%")
plt.suptitle("Gender vs Risk Class"); plt.tight_layout(); plt.show()

# =============================================================================
# BLOCK 10: INVESTMENT AVENUE VISUALISATIONS
# =============================================================================
n_feat = len(avail_rank)
n_cols = 3
n_rows = (n_feat + n_cols - 1) // n_cols
df_plot = df[avail_rank + ['Risk_Class']].copy()
df_plot['Risk_Label'] = df_plot['Risk_Class'].map(label_names)

fig, axes = plt.subplots(n_rows, n_cols, figsize=(6*n_cols, 4*n_rows), constrained_layout=True)
axes = axes.flatten()
for idx, feat in enumerate(avail_rank):
    sns.boxplot(data=df_plot, x='Risk_Label', y=feat, order=order_labels,
                palette=named_pal, ax=axes[idx])
    axes[idx].set_title(feat)
for idx in range(n_feat, len(axes)): axes[idx].set_visible(False)
fig.suptitle("Box plots: Investment avenue preference per risk class")
plt.show()

means = df.groupby('Risk_Class')[avail_rank].mean().round(2)
means.index = [label_names[i] for i in means.index]
x = np.arange(len(avail_rank)); width = 0.25
fig4, ax4 = plt.subplots(figsize=(14, 5))
for i, lbl in enumerate(order_ids):
    ax4.bar(x + i*width, means.loc[label_names[lbl]], width,
            label=label_names[lbl], color=palette[lbl], edgecolor='black', alpha=0.85)
ax4.set_xticks(x + width)
ax4.set_xticklabels(avail_rank, rotation=45, ha='right')
ax4.set_ylabel("Mean Value"); ax4.set_title("Mean Investment Avenue Preference per Risk Class")
ax4.legend(); plt.tight_layout(); plt.show()

# =============================================================================
# BLOCK 11: SUPERVISED MODEL — PREPARE DATA
#
# The supervised model trains on SUPERVISED_FEATURES only (no rank cols,
# no reason cols). This means the model learns to predict risk class from
# demographics and stated investment intent — not from the portfolio itself.
# This is intentional: it allows classifying new investors before knowing
# their actual investment allocations.
# =============================================================================
X = df[SUPERVISED_FEATURES].values.astype(float)
y = df['Risk_Class'].values

print("\n=== CLASS DISTRIBUTION ===")
for lbl in order_ids:
    cnt = (y == lbl).sum()
    print(f"  {label_names[lbl]:12}: {cnt:5} ({cnt/len(y)*100:.1f}%)")

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y)
X_train_arr = X_train.astype(float)
X_test_arr  = X_test.astype(float)
y_train_np  = y_train.flatten()
y_test_np   = y_test.flatten()
target_names = [label_names[i] for i in order_ids]
print(f"\nTrain: {X_train_arr.shape[0]}, Test: {X_test_arr.shape[0]}")

# =============================================================================
# BLOCK 12: SMOTE AND UNDERSAMPLING VARIANTS
# =============================================================================
sm = SMOTE(random_state=42, k_neighbors=5)
X_sm, y_sm = sm.fit_resample(X_train_arr, y_train_np)
y_sm = y_sm.flatten()
print(f"SMOTE training size: {X_sm.shape[0]}")

rus = RandomUnderSampler(random_state=42)
X_us, y_us = rus.fit_resample(X_train_arr, y_train_np)
y_us = y_us.flatten()
print(f"Undersampled training size: {X_us.shape[0]}")

# =============================================================================
# BLOCK 13: EVALUATION FUNCTION
# =============================================================================
def evaluate_phase(name, X_tr, y_tr, use_class_weight=False, cmap='Blues'):
    print(f"\n{'='*70}\n{name}\n{'='*70}")
    print(f"{'Model':<18} | {'Accuracy':>10} | {'Balanced Acc':>13} | {'Macro F1':>10}")
    print("-" * 60)
    results = {}

    rf = RandomForestClassifier(n_estimators=100, max_depth=4, random_state=42,
                                class_weight='balanced' if use_class_weight else None)
    rf.fit(X_tr, y_tr)
    yp = rf.predict(X_test_arr).flatten()
    acc, bal, f1 = accuracy_score(y_test_np, yp), balanced_accuracy_score(y_test_np, yp), f1_score(y_test_np, yp, average='macro')
    print(f"{'Random Forest':<18} | {acc:>10.4f} | {bal:>13.4f} | {f1:>10.4f}")
    results['Random Forest'] = {'model': rf, 'y_pred': yp, 'acc': acc, 'bal_acc': bal, 'f1': f1}

    xgb = XGBClassifier(n_estimators=100, max_depth=4, random_state=42,
                        eval_metric='mlogloss', use_label_encoder=False)
    sw = compute_sample_weight('balanced', y=y_tr) if use_class_weight else None
    xgb.fit(X_tr, y_tr, sample_weight=sw)
    yp = xgb.predict(X_test_arr).flatten()
    acc, bal, f1 = accuracy_score(y_test_np, yp), balanced_accuracy_score(y_test_np, yp), f1_score(y_test_np, yp, average='macro')
    print(f"{'XGBoost':<18} | {acc:>10.4f} | {bal:>13.4f} | {f1:>10.4f}")
    results['XGBoost'] = {'model': xgb, 'y_pred': yp, 'acc': acc, 'bal_acc': bal, 'f1': f1}

    cb = CatBoostClassifier(iterations=100, depth=4, verbose=0, random_state=42)
    cb.fit(X_tr, y_tr, sample_weight=sw)
    yp = cb.predict(X_test_arr).flatten()
    acc, bal, f1 = accuracy_score(y_test_np, yp), balanced_accuracy_score(y_test_np, yp), f1_score(y_test_np, yp, average='macro')
    print(f"{'CatBoost':<18} | {acc:>10.4f} | {bal:>13.4f} | {f1:>10.4f}")
    results['CatBoost'] = {'model': cb, 'y_pred': yp, 'acc': acc, 'bal_acc': bal, 'f1': f1}

    for model_name, res in results.items():
        print(f"\n--- {model_name} classification report ---")
        print(classification_report(y_test_np, res['y_pred'], target_names=target_names))

    fig, axes = plt.subplots(1, 3, figsize=(18, 5))
    for ax, (model_name, res) in zip(axes, results.items()):
        cm = confusion_matrix(y_test_np, res['y_pred'], labels=order_ids)
        sns.heatmap(pd.DataFrame(cm,
                    index=[f"True:{label_names[i]}" for i in order_ids],
                    columns=[f"Pred:{label_names[i]}" for i in order_ids]),
                    annot=True, fmt='d', cmap=cmap, ax=ax, annot_kws={'size': 11, 'weight': 'bold'})
        ax.set_title(f"{model_name}\n({name})", fontsize=11, fontweight='bold')
    plt.suptitle(f"Confusion matrices – {name}", fontsize=12, fontweight='bold')
    plt.tight_layout(); plt.show()
    return results


# =============================================================================
# BLOCK 14: FOUR-WAY BALANCING COMPARISON
# =============================================================================
phase1 = evaluate_phase("PHASE 1: NO BALANCING",       X_train_arr, y_train_np, use_class_weight=False, cmap='Greys')
phase2 = evaluate_phase("PHASE 2: CLASS WEIGHTING",    X_train_arr, y_train_np, use_class_weight=True,  cmap='Blues')
phase3 = evaluate_phase("PHASE 3: SMOTE",              X_sm,        y_sm,       use_class_weight=False, cmap='Greens')
phase4 = evaluate_phase("PHASE 4: UNDERSAMPLING",      X_us,        y_us,       use_class_weight=False, cmap='Blues')

print("\n" + "=" * 70)
print("FOUR-WAY COMPARISON")
print("=" * 70)
for model in ['Random Forest', 'XGBoost', 'CatBoost']:
    print(f"\n{model}")
    print(f"{'Metric':<15} {'No Bal':>10} {'CW Only':>10} {'SMOTE':>10} {'Undersamp':>12}")
    print("-" * 57)
    for metric, key in [('Accuracy', 'acc'), ('Balanced Acc', 'bal_acc'), ('Macro F1', 'f1')]:
        print(f"{metric:<15} {phase1[model][key]:>10.4f} {phase2[model][key]:>10.4f} "
              f"{phase3[model][key]:>10.4f} {phase4[model][key]:>12.4f}")

# =============================================================================
# BLOCK 15: CROSS-VALIDATION — CATBOOST + UNDERSAMPLING
# =============================================================================
from sklearn.metrics import make_scorer

print("\n" + "=" * 70)
print("CROSS-VALIDATION — CATBOOST + UNDERSAMPLING")
print("=" * 70)

best_model = CatBoostClassifier(iterations=100, depth=4,
                                verbose=0, random_state=42)

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

bal_scores = cross_val_score(best_model, X_us, y_us, cv=cv,
                             scoring='balanced_accuracy')
f1_scores  = cross_val_score(best_model, X_us, y_us, cv=cv,
                             scoring=make_scorer(f1_score, average='macro'))

print(f"Balanced Accuracy: {bal_scores.mean():.4f} ± {bal_scores.std():.4f}")
print(f"Macro F1:          {f1_scores.mean():.4f} ± {f1_scores.std():.4f}")

best_model.fit(X_us, y_us)
final_pred    = best_model.predict(X_test_arr)
final_bal_acc = balanced_accuracy_score(y_test_np, final_pred)
final_f1      = f1_score(y_test_np, final_pred, average='macro')
print(f"\nTest set: Balanced Acc = {final_bal_acc:.4f}, Macro F1 = {final_f1:.4f}")
print(classification_report(y_test_np, final_pred, target_names=target_names))

# =============================================================================
# BLOCK 16: CATBOOST + UNDERSAMPLING — CONFUSION MATRIX
# =============================================================================

best_cb = CatBoostClassifier(iterations=100, depth=4, verbose=0, random_state=42)
best_cb.fit(X_us, y_us)
cb_pred = best_cb.predict(X_test_arr).flatten()

# Confusion matrix
cm = confusion_matrix(y_test_np, cb_pred, labels=order_ids)
fig, ax = plt.subplots(figsize=(7, 5))
sns.heatmap(pd.DataFrame(cm,
            index=[f"True:{label_names[i]}" for i in order_ids],
            columns=[f"Pred:{label_names[i]}" for i in order_ids]),
            annot=True, fmt='d', cmap='Blues', ax=ax,
            annot_kws={'size': 12, 'weight': 'bold'})
ax.set_title("CatBoost + Undersampling — Confusion Matrix", fontweight='bold')
plt.tight_layout()
plt.savefig('confusion_matrix_catboost.png', dpi=150, bbox_inches='tight')
plt.show()

# Per-class numbers
print("=== CatBoost + Undersampling: Per-class breakdown ===")
print(classification_report(y_test_np, cb_pred, target_names=target_names))
for i, lbl in enumerate(order_ids):
    total = (y_test_np == i).sum()
    correct = cm[i, i]
    print(f"{label_names[i]}: {correct}/{total} correct ({correct/total*100:.1f}%)")

# =============================================================================
# BLOCK 17: SHAP ANALYSIS — CATBOOST + UNDERSAMPLING
# =============================================================================
import shap

explainer = shap.TreeExplainer(best_cb)
shap_values = explainer.shap_values(X_test_arr)

# shap_values is shape (n_samples, n_features, n_classes) for CatBoost
# Plot beeswarm for each class
class_labels = ['Conservative', 'Moderate', 'Aggressive']
fig, axes = plt.subplots(1, 3, figsize=(22, 7))

for i, cls in enumerate(class_labels):
    plt.sca(axes[i])
    shap.summary_plot(
        shap_values[:, :, i],
        X_test_arr,
        feature_names=SUPERVISED_FEATURES,
        show=False,
        plot_size=None
    )
    axes[i].set_title(f'SHAP — {cls}', fontsize=12, fontweight='bold')

plt.suptitle("SHAP Beeswarm Plots: CatBoost + Undersampling", fontsize=14, fontweight='bold')
plt.tight_layout()
plt.savefig('shap_catboost.png', dpi=150, bbox_inches='tight')
plt.show()

# Print mean absolute SHAP values per feature per class
print("\n=== Mean |SHAP| per feature per class ===")
for i, cls in enumerate(class_labels):
    mean_shap = pd.Series(
        np.abs(shap_values[:, :, i]).mean(axis=0),
        index=SUPERVISED_FEATURES
    ).sort_values(ascending=False)
    print(f"\n{cls}:")
    print(mean_shap.round(4).to_string())

"""analysis of the investors after prediction"""

# Predicted label heatmap on test set
rank_cols_plot = ['Mutual_Funds', 'Equity_Market', 'Debentures',
                  'Government_Bonds', 'Fixed_Deposits', 'PPF', 'Gold']

# Get the test set rows from df using the same split
df_test = df.iloc[y_test.index if hasattr(y_test, 'index') else
                  train_test_split(range(len(df)), test_size=0.2,
                  random_state=42, stratify=df['Risk_Class'].values)[1]]

df_test = df_test.copy()
df_test['Predicted_Class'] = final_pred  # CatBoost predictions

pred_profiles = df_test.groupby('Predicted_Class')[rank_cols_plot].mean().round(2)
pred_profiles.index = [label_names[i] for i in pred_profiles.index]

plt.figure(figsize=(10, 4))
sns.heatmap(pred_profiles.T, annot=True, fmt=".2f", cmap="Blues")
plt.title("Mean Investment Avenue Preference per Predicted Risk Class (Test Set)")
plt.tight_layout()
plt.savefig('predicted_heatmap.png', dpi=150, bbox_inches='tight')
plt.show()

# Find investors where predicted and true labels disagree
# and look at their stated vs revealed features

import pandas as pd
import numpy as np

# Get test set
X_test_df = pd.DataFrame(X_test_arr, columns=SUPERVISED_FEATURES)
X_test_df['True_Label'] = y_test_np
X_test_df['Pred_Label'] = final_pred

# Get the ranking features for the same test investors
# Need to reconstruct test indices
from sklearn.model_selection import train_test_split
indices = np.arange(len(df))
train_idx, test_idx = train_test_split(
    indices, test_size=0.2, random_state=42, stratify=df['Risk_Class'].values)

rank_cols = ['Mutual_Funds','Equity_Market','Debentures',
             'Government_Bonds','Fixed_Deposits','PPF','Gold']

df_test_full = df.iloc[test_idx].copy()
df_test_full['True_Label'] = y_test_np
df_test_full['Pred_Label'] = final_pred
df_test_full['Correct'] = (df_test_full['True_Label'] == df_test_full['Pred_Label'])

# Compare mean ranking scores for correct vs misclassified investors
print("=== CORRECTLY CLASSIFIED ===")
print(df_test_full[df_test_full['Correct']][rank_cols].mean().round(2))

print("\n=== MISCLASSIFIED ===")
print(df_test_full[~df_test_full['Correct']][rank_cols].mean().round(2))

# Specifically: predicted Conservative but true Moderate
con_pred_mod_true = df_test_full[
    (df_test_full['Pred_Label']==0) & (df_test_full['True_Label']==1)]
print(f"\n=== PREDICTED CONSERVATIVE, TRUE MODERATE (n={len(con_pred_mod_true)}) ===")
print("Ranking behavior:")
print(con_pred_mod_true[rank_cols].mean().round(2))
print("Stated preferences:")
stated = ['Objective_Score','Avenue_Score','Expect_Score',
          'Duration_Score','Monitor_Score']
print(con_pred_mod_true[stated].mean().round(2))

"""the 5 fold cv on all the dataset and not onlt on the undersampled data"""

# =============================================================================
# BLOCK 19: CORRECT CROSS-VALIDATION — UNDERSAMPLE INSIDE EACH FOLD
# =============================================================================
from sklearn.pipeline import Pipeline
from imblearn.pipeline import Pipeline as ImbPipeline
from sklearn.metrics import make_scorer

print("\n" + "="*70)
print("CORRECTED CROSS-VALIDATION — UNDERSAMPLING INSIDE EACH FOLD")
print("="*70)

# Use the FULL training set (not pre-undersampled)
# Undersampling is applied inside each fold only to the training portion
correct_cv_pipeline = ImbPipeline([
    ('undersample', RandomUnderSampler(random_state=42)),
    ('classifier', CatBoostClassifier(iterations=100, depth=4,
                                      verbose=0, random_state=42))
])

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

# Balanced accuracy per fold
bal_scores_correct = cross_val_score(
    correct_cv_pipeline,
    X_train_arr, y_train_np,
    cv=cv,
    scoring='balanced_accuracy'
)

# Macro F1 per fold
f1_scores_correct = cross_val_score(
    correct_cv_pipeline,
    X_train_arr, y_train_np,
    cv=cv,
    scoring=make_scorer(f1_score, average='macro')
)

print(f"Balanced Accuracy: {bal_scores_correct.mean():.4f} "
      f"± {bal_scores_correct.std():.4f}")
print(f"Scores: {bal_scores_correct.round(4)}")
print()
print(f"Macro F1:          {f1_scores_correct.mean():.4f} "
      f"± {f1_scores_correct.std():.4f}")
print(f"Scores: {f1_scores_correct.round(4)}")

print("\n=== COMPARISON ===")
print(f"{'Method':<35} {'Bal Acc':>10} {'Macro F1':>10}")
print("-"*57)
print(f"{'CV on undersampled set (original)':<35} "
      f"{bal_scores.mean():>10.4f} {f1_scores.mean():>10.4f}")
print(f"{'CV with undersampling inside fold':<35} "
      f"{bal_scores_correct.mean():>10.4f} "
      f"{f1_scores_correct.mean():>10.4f}")
print(f"{'Test set (CatBoost + undersampling)':<35} "
      f"{final_bal_acc:>10.4f} {final_f1:>10.4f}")

"""traditional ways on my dataset"""

# =============================================================================
# BLOCK 18: RULE-BASED BASELINE (traditional questionnaire approach)
# =============================================================================
# Simulates a psychometric scoring approach using only stated-preference
# ordinal features — mimicking what a traditional questionnaire would use

# Use the original df with ordinal scores already computed
rule_features = ['Duration_Score', 'Expect_Score', 'Monitor_Score',
                 'Objective_Score', 'Avenue_Score']

# Simple sum score — higher = more aggressive
df['Rule_Score'] = df[rule_features].sum(axis=1)

# Score range: min = 5 (all conservative), max = 17 (all aggressive)
# Divide into 3 equal-width bins
score_min = df['Rule_Score'].min()
score_max = df['Rule_Score'].max()
bin_width = (score_max - score_min) / 3

df['Rule_Class'] = pd.cut(
    df['Rule_Score'],
    bins=[score_min - 0.01,
          score_min + bin_width,
          score_min + 2 * bin_width,
          score_max + 0.01],
    labels=[0, 1, 2]
).astype(int)

# Evaluate on the same test set indices
# Need to align with X_test indices
test_idx = y_test.index if hasattr(y_test, 'index') else None

# Rebuild using the test split
from sklearn.model_selection import train_test_split
rule_y = df['Rule_Class'].values
_, rule_y_test = train_test_split(
    rule_y, test_size=0.2, random_state=42,
    stratify=df['Risk_Class'].values
)

print("=== RULE-BASED BASELINE (traditional approach) ===")
print(classification_report(y_test_np, rule_y_test,
                             target_names=target_names))
print(f"Balanced Accuracy: {balanced_accuracy_score(y_test_np, rule_y_test):.4f}")
print(f"Macro F1:          {f1_score(y_test_np, rule_y_test, average='macro'):.4f}")

print("\n=== COMPARISON: Baseline vs CatBoost + Undersampling ===")
print(f"{'Metric':<20} {'Rule-Based':>12} {'CatBoost+US':>12}")
print("-" * 46)
print(f"{'Balanced Accuracy':<20} "
      f"{balanced_accuracy_score(y_test_np, rule_y_test):>12.4f} "
      f"{balanced_accuracy_score(y_test_np, final_pred):>12.4f}")
print(f"{'Macro F1':<20} "
      f"{f1_score(y_test_np, rule_y_test, average='macro'):>12.4f} "
      f"{f1_score(y_test_np, final_pred, average='macro'):>12.4f}")
print(f"{'Accuracy':<20} "
      f"{accuracy_score(y_test_np, rule_y_test):>12.4f} "
      f"{accuracy_score(y_test_np, final_pred):>12.4f}")

# =============================================================================
# BLOCK 16: SAVE AND DOWNLOAD FINAL DEPLOYMENT MODEL
# =============================================================================

!pip install joblib -q
!pip install catboost -q

import joblib
import json
import sys
import sklearn
import catboost
import imblearn
import xgboost
from google.colab import files

# -----------------------------------------------------------------------------
# 1. SAVE TRAINED CATBOOST MODEL
# -----------------------------------------------------------------------------

MODEL_NAME = "catboost_undersampling_risk_model.pkl"

joblib.dump(best_model, MODEL_NAME)

print(f"Model saved as: {MODEL_NAME}")

# -----------------------------------------------------------------------------
# 2. SAVE FEATURE NAMES USED BY THE MODEL
# -----------------------------------------------------------------------------

feature_info = {
    "model_features": SUPERVISED_FEATURES
}

with open("model_features.json", "w") as f:
    json.dump(feature_info, f, indent=4)

print("model_features.json saved")

# -----------------------------------------------------------------------------
# 3. SAVE PACKAGE / ENVIRONMENT INFO
# -----------------------------------------------------------------------------

requirements_info = {
    "python_version": sys.version,
    "libraries": {
        "scikit-learn": sklearn.__version__,
        "catboost": catboost.__version__,
        "imbalanced-learn": imblearn.__version__,
        "xgboost": xgboost.__version__,
        "joblib": joblib.__version__,
        "pandas": pd.__version__,
        "numpy": np.__version__,
        "seaborn": sns.__version__
    }
}

with open("requirements_info.json", "w") as f:
    json.dump(requirements_info, f, indent=4)

print("requirements_info.json saved")

# -----------------------------------------------------------------------------
# 4. SAVE INPUT SCHEMA
# -----------------------------------------------------------------------------

input_schema = []

for col in SUPERVISED_FEATURES:

    col_data = df[col]

    feature_entry = {
        "feature_name": col,
        "dtype": str(col_data.dtype),
        "missing_values": int(col_data.isnull().sum())
    }

    # Add numeric range if numeric
    if pd.api.types.is_numeric_dtype(col_data):
        feature_entry["min"] = float(col_data.min())
        feature_entry["max"] = float(col_data.max())

    input_schema.append(feature_entry)

with open("input_schema.json", "w") as f:
    json.dump(input_schema, f, indent=4)

print("input_schema.json saved")

# -----------------------------------------------------------------------------
# 5. SAVE OUTPUT SCHEMA
# -----------------------------------------------------------------------------

output_schema = {
    "target_variable": "Risk_Class",
    "class_mapping": {
        "0": "Conservative",
        "1": "Moderate",
        "2": "Aggressive"
    },
    "prediction_output": {
        "predicted_class": "integer",
        "predicted_label": "string",
        "class_probabilities": {
            "Conservative": "float",
            "Moderate": "float",
            "Aggressive": "float"
        }
    }
}

with open("output_schema.json", "w") as f:
    json.dump(output_schema, f, indent=4)

print("output_schema.json saved")

# -----------------------------------------------------------------------------
# 6. SAVE SAMPLE INPUT JSON
# -----------------------------------------------------------------------------

sample_input = pd.DataFrame(
    [X_test_arr[0]],
    columns=SUPERVISED_FEATURES
)

sample_input_dict = sample_input.iloc[0].to_dict()

with open("sample_input.json", "w") as f:
    json.dump(sample_input_dict, f, indent=4)

print("sample_input.json saved")

# -----------------------------------------------------------------------------
# 7. SAVE SAMPLE OUTPUT JSON
# -----------------------------------------------------------------------------

sample_prediction = int(best_model.predict(sample_input)[0])

sample_probabilities = best_model.predict_proba(sample_input)[0]

sample_output = {
    "predicted_class": sample_prediction,
    "predicted_label": label_names[sample_prediction],
    "class_probabilities": {
        "Conservative": float(sample_probabilities[0]),
        "Moderate": float(sample_probabilities[1]),
        "Aggressive": float(sample_probabilities[2])
    }
}

with open("sample_output.json", "w") as f:
    json.dump(sample_output, f, indent=4)

print("sample_output.json saved")

# -----------------------------------------------------------------------------
# 8. SAVE MODEL LOADER SCRIPT
# -----------------------------------------------------------------------------

loader_script = """
import joblib
import pandas as pd

MODEL_PATH = "catboost_undersampling_risk_model.pkl"

FEATURES = """ + str(SUPERVISED_FEATURES) + """

label_names = {
    0: "Conservative",
    1: "Moderate",
    2: "Aggressive"
}

def load_model():
    model = joblib.load(MODEL_PATH)
    return model

def predict_risk(input_json):

    model = load_model()

    input_df = pd.DataFrame([input_json])

    prediction = int(model.predict(input_df)[0])

    probabilities = model.predict_proba(input_df)[0]

    return {
        "predicted_class": prediction,
        "predicted_label": label_names[prediction],
        "class_probabilities": {
            "Conservative": float(probabilities[0]),
            "Moderate": float(probabilities[1]),
            "Aggressive": float(probabilities[2])
        }
    }

print("Model loader ready.")
"""

with open("load_model.py", "w") as f:
    f.write(loader_script)

print("load_model.py saved")

# -----------------------------------------------------------------------------
# 9. DOWNLOAD ALL FILES
# -----------------------------------------------------------------------------

download_files = [
    MODEL_NAME,
    "model_features.json",
    "requirements_info.json",
    "input_schema.json",
    "output_schema.json",
    "sample_input.json",
    "sample_output.json",
    "load_model.py"
]

for file in download_files:
    files.download(file)

print("\nAll deployment files downloaded successfully.")

